### ISSUE TITLE
May break on CTRL+C

### ISSUE THREAD

**Issue by doudou** [piotrmurach/tty-progressbar#14]
When I interrupt my script with CTRL+C, it seems that tty-progressbar goes through #require which is forbidden in trap context

Backtrace

```
/home/doudou/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:187:in `lock': can't be called from trap context (ThreadError)
        from /home/doudou/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:187:in `mon_enter'
        from /home/doudou/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-screen-0.4.3/lib/tty/screen/size.rb:49:in `try_io_console'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-screen-0.4.3/lib/tty/screen/size.rb:37:in `from_io_console'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-screen-0.4.3/lib/tty/screen/size.rb:21:in `size'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-screen-0.4.3/lib/tty/screen.rb:46:in `size'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-screen-0.4.3/lib/tty/screen.rb:28:in `size'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-screen-0.4.3/lib/tty/screen.rb:33:in `width'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-progressbar-0.7.0/lib/tty/progressbar.rb:266:in `max_columns'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/tty-progressbar-0.7.0/lib/tty/progressbar.rb:289:in `block in register_callbacks'
        from /home/doudou/dev/flat_fish/tools/pocolog/lib/pocolog/file.rb:739:in `read'
        from /home/doudou/dev/flat_fish/tools/pocolog/lib/pocolog/file.rb:739:in `data_header'
        from /home/doudou/dev/flat_fish/tools/pocolog/lib/pocolog/data_reader.rb:307:in `advance'
        from /home/doudou/dev/flat_fish/tools/log_tools/lib/log_tools/file_upgrader.rb:62:in `block in upgrade'
        from /home/doudou/dev/flat_fish/tools/log_tools/lib/log_tools/file_upgrader.rb:28:in `each'
        from /home/doudou/dev/flat_fish/tools/log_tools/lib/log_tools/file_upgrader.rb:28:in `upgrade'
        from /home/doudou/dev/flat_fish/tools/log_tools/lib/log_tools/cli.rb:39:in `block in upgrade'
        from /home/doudou/dev/flat_fish/tools/log_tools/lib/log_tools/cli.rb:30:in `each'
        from /home/doudou/dev/flat_fish/tools/log_tools/lib/log_tools/cli.rb:30:in `upgrade'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/doudou/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/doudou/dev/flat_fish/tools/log_tools/bin/rock-log:3:in `<main>'
```

**Comment by piotrmurach** [comment]
Hi Sylvain, it seems from the backtrace that offending code is in `register_callbacks` method. However, this has been removed in the lastest `v0.9.0`, and hence there should not be any signal trapping in the code base itself. Would you mind installing that version and testing if the issue persists?

**Comment by doudou** [comment]
Ooops. Sorry, I did not check whether I was using the latest version. Will test !

**Comment by piotrmurach** [comment]
Does the problem still persist?

**Comment by doudou** [comment]
Didn't have the time to check :(. I'll come back to you when I do. If you prefer, just close this, I'll reopen if I still have the problem.

**Comment by piotrmurach** [comment]
No worries, I'm in the process preparing tty components for another release and wanted to include as many bug fixes as possible, including this one. I'm comfortable with it staying open though until you find time to test.

**Comment by doudou** [comment]
The problem indeed seem to have gone away on 1.9. Thanks !
